config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others 	available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: %i[ show edit update destroy ]

	def index
		@users = User.all 
	end

	def show; end

	def edit; end

	def new 
		@user = User.new
	end

	def create
		user = @user.create!(params_user)
		render json: user
	end

	def update
		@user.update!(params_user)

		render json: 'Atualizado com sucesso!'
	end

	def destroy
		@user.destroy
	end

	private 

	def set_user
		@user = User.find params[:id] 
	end

	def params_user
		params.require(:user).permit(:name, :email, :encrypted_password, :reset_password, :foto)
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crudzinho</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<title>Crudzinho</title>
  <header>
    <h1>Usuários</h1>
  </header>
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Foto</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user|%>
        <tr>
          <th><%= user.name %></th>
          <th><%= user.email %></th>
          <th><%= user.foto %></th>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br/>

<%= link_to 'Novo Usuário', new_user_path %>